### ISSUE TITLE
Service with keyword "foreach" and "user" in src and dst isn't shown correctly

### ISSUE THREAD

**Issue by hknutzen** [hknutzen/Netspoc-Web#19]
* Semantic of a service is changed, if attribute "foreach" is given. Hence "foreach" should be shown in web view.
* Automatic groups with "user", e.g. "any:[user]" are currently not shown at all. Only "user" is shown. This should be fixed by showing the original definition of automatic group with user.

**Comment by gbaro** [comment]
Hallo Heinz,
irgendwie lustig, von Git-Hub scheinen nur die Netspoc-Mails nicht bei mir anzukommen :-(
Mein neuer Rechner hat Limpus Linux. 
 Viele Grüße,

Gaby

      Von: Heinz Knutzen <notifications@github.com>
 An: hknutzen/Netspoc-Web <Netspoc-Web@noreply.github.com> 
 Gesendet: 9:15 Mittwoch, 4.Februar 2015
 Betreff: [Netspoc-Web] Service with keyword "foreach" and "user" in src and dst isn't shown correctly (#19)
   
   
   - Semantic of a service is changed, if attribute "foreach" is given. Hence "foreach" should be shown in web view.
   - Automatic groups with "user", e.g. "any:[user]" are currently not shown at all. Only "user" is shown. This should be fixed by showing the original definition of automatic group with user.

**Comment by orrence** [comment]
This has been resolved with a commit for "Netspoc":
https://github.com/hknutzen/Netspoc/commit/72f49ce24a8c1a848b202991335287f6e742dc8b
